- name: Set variables
  set_fact:
    desired_version: "v5.29.0"  # ArgoCD version to install
    admin_password: "$2y$10$jfkwzgL1zA/QwuVixBowr.EJH1FghSCIHW7I58dZxjLt8e2lqAyKO"     # Admin password for ArgoCD
    
- name: Ensure ArgoCD Helm repo is added
  command: >
    helm repo add argo https://argoproj.github.io/argo-helm
  register: helm_repo_add
  failed_when: false
  changed_when: "'already exists' not in helm_repo_add.stderr"

- name: Update Helm repositories
  command: helm repo update

- name: Check if ArgoCD is already installed
  command: helm list --namespace argocd --kube-context "kind-{{ cluster.name }}"
  register: helm_installed
  failed_when: false
  changed_when: false

- name: Install ArgoCD if not installed
  command: >
    helm install argocd argo/argo-cd
    --version "{{ desired_version }}"
    --namespace argocd
    --create-namespace
    --set server.service.type=NodePort
    --set server.service.nodePort="{{ cluster.argocd_nodeport }}"
    --set configs.secret.argocdServerAdminPassword="{{ admin_password }}" 
    --kube-context kind-{{ cluster.name }}
  when: "'argocd' not in helm_installed.stdout"

- name: Patch NodePort for ArgoCD server
  shell: |
    kubectl --context kind-{{ cluster.name }} -n argocd patch svc argocd-server \
    -p '{"spec": {"type": "NodePort", "ports": [{"port": 443, "targetPort": 8080, "nodePort": {{ cluster.argocd_nodeport }} }]}}'

# - name: Set ArgoCD admin password
#   shell: |
#     kubectl -n argocd get secret argocd-secret --kube-context "{{ cluster.kubecontext }}" --kubeconfig="{{ cluster.kubeconfig }}" || \
#     kubectl -n argocd patch secret argocd-secret \
#     -p "{\"data\": {\"admin.password\": \"{{ admin_password | b64encode }}\"}}"
#   environment:
#     KUBECONFIG: "{{ cluster.kubeconfig }}"    
 